# Generated by Django 5.1.4 on 2025-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0007_profile_facebook_link_profile_homepage_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
